spring:
  profiles: dev

  activemq:
    brokerURL: tcp://localhost:61616
    inMemory: false

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reader
    username: root
    password:

  jpa:
     show-sql: true
     hibernate:
       ddl-auto: update
