spring:
  application:
    name: JavaguruReaderFetcher
  profiles:
    active: development
  main:
    web-environment: false
    show_banner: false

---

spring:
  profiles: development
  activemq:
    brokerURL: tcp://localhost:61616
    inMemory: false

---

spring:
  profiles: test
