databaseChangeLog:
  - property:
      name: now()
      value: now()
      dbms: h2,mysql
  - property:
      name: now()
      value: current_timestamp
      dbms: postresql
  - include:
      file: classpath:config/liquibase/changelog/db-changelog-002.xml
      relativeToChangelogFile: false
      
